name: Changeset PR CI Trigger

# This workflow ensures CI runs on changeset release PRs
# Even if created by bots (which sometimes don't trigger CI automatically)
on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  trigger-ci:
    name: Ensure CI Runs on Changeset PRs
    runs-on: ubuntu-latest
    # Only run for changeset release PRs created by the GitHub bot
    if: |
      github.event.pull_request.user.login == 'github-actions[bot]' &&
      startsWith(github.event.pull_request.head.ref, 'changeset-release/')
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if CI is running
        id: check-ci
        run: |
          # Wait a moment for CI to potentially start
          sleep 10

          # Check if there are any check runs for this SHA
          CHECK_COUNT=$(gh api \
            repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs \
            --jq '.total_count')

          echo "check_count=$CHECK_COUNT" >> $GITHUB_OUTPUT

          if [ "$CHECK_COUNT" -eq "0" ]; then
            echo "❌ No CI checks found, will trigger CI"
            echo "needs_trigger=true" >> $GITHUB_OUTPUT
          else
            echo "✅ CI is already running ($CHECK_COUNT checks found)"
            echo "needs_trigger=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger CI with empty commit
        if: steps.check-ci.outputs.needs_trigger == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create an empty commit to trigger CI
          git commit --allow-empty -m "chore: trigger CI for changeset release PR [skip ci]"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: steps.check-ci.outputs.needs_trigger == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🤖 **CI Trigger Bot**

          I've detected this is a changeset release PR without CI checks running.
          An empty commit has been pushed to trigger the CI workflow.

          This is an automated action to ensure all release PRs pass CI before merging."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}