name: ADHD CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: "20.18.1"
  PNPM_VERSION: "9.15.4"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

jobs:
  setup:
    name: 🔧 Setup & Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .eslintcache
            .prettiercache
            .turbo
            **/.turbo
          key: deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-turbo-${{ hashFiles('turbo.json*', 'tsconfig*.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
            deps-${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline

  quick-tests:
    name: ⚡ Quick Tests (1m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:smoke

  focused-tests:
    name: 🎯 Focused Tests (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:focused

  format:
    name: 💅 Format (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm format:check

  lint:
    name: 🔍 Lint (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm lint

  typecheck:
    name: 🔧 Types (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages for type resolution
        run: pnpm build
      - run: pnpm typecheck

  build:
    name: 🏗️ Build (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build

  commit-lint:
    name: ⚧ Commit Lint (5m)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD --verbose

  ci-status:
    name: 📊 CI Status
    runs-on: ubuntu-latest
    needs: [quick-tests, focused-tests, format, lint, typecheck, build, commit-lint]
    if: always()
    steps:
      - name: Generate Enhanced Status Report
        run: |
          echo "🎯 ADHD-Optimized CI Pipeline Status"
          echo "📊 CI Pipeline Status Summary"
          echo "$([[ "${{ needs.quick-tests.result }}" == "success" ]] && echo "✅" || echo "❌") Quick Tests: ${{ needs.quick-tests.result }}"
          echo "$([[ "${{ needs.focused-tests.result }}" == "success" ]] && echo "✅" || echo "❌") Focused Tests: ${{ needs.focused-tests.result }}"
          echo "$([[ "${{ needs.format.result }}" == "success" ]] && echo "✅" || echo "❌") Format: ${{ needs.format.result }}"
          echo "$([[ "${{ needs.lint.result }}" == "success" ]] && echo "✅" || echo "❌") Lint: ${{ needs.lint.result }}"
          echo "$([[ "${{ needs.typecheck.result }}" == "success" ]] && echo "✅" || echo "❌") Types: ${{ needs.typecheck.result }}"
          echo "$([[ "${{ needs.build.result }}" == "success" ]] && echo "✅" || echo "❌") Build: ${{ needs.build.result }}"
          echo "$([[ "${{ needs.commit-lint.result }}" == "success" ]] && echo "✅" || echo "❌") Commit Lint: ${{ needs.commit-lint.result }}"
          
          # Add breadcrumb navigation and progress tracking
          echo "📍 Step 7/7 - Pipeline Status Check"
          echo "🧭 Navigation: Setup → Tests → Quality → Build → Status"
          
          # Include fix command infrastructure
          echo "🔧 Fix Commands Available:"
          echo "  - Lint: pnpm lint:fix"
          echo "  - Format: pnpm format"
          echo "  - Types: pnpm typecheck"
          echo "  - Tests: pnpm test"
          echo "include-fix-commands: true"
          
          # Failure recovery hints and status reporting
          if [[ "${{ needs.quick-tests.result }}" == "failure" || "${{ needs.focused-tests.result }}" == "failure" || "${{ needs.format.result }}" == "failure" || "${{ needs.lint.result }}" == "failure" || "${{ needs.typecheck.result }}" == "failure" || "${{ needs.build.result }}" == "failure" || "${{ needs.commit-lint.result }}" == "failure" ]]; then
            echo "❌ CI Pipeline failed"
            echo "status-reporter: failure detected"
            exit 1
          fi
          echo "✅ All CI checks passed!"
          echo "status-reporter: all-success"