name: ADHD CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: "20.18.1"
  PNPM_VERSION: "9.15.4"

jobs:
  setup:
    name: 🔧 Setup & Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .eslintcache
            .prettiercache
            .turbo
          key: deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-turbo-${{ hashFiles('turbo.json*', 'tsconfig*.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
            deps-${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline

  quick-tests:
    name: ⚡ Quick Tests (1m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:smoke

  focused-tests:
    name: 🎯 Focused Tests (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  format:
    name: 💅 Format (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm format:check

  lint:
    name: 🔍 Lint (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  types:
    name: 🔧 Types (5m)
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  commit-lint:
    name: ⚧ Commit Lint (5m)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD --verbose

  ci-status:
    name: 📊 CI Status
    runs-on: ubuntu-latest
    needs: [quick-tests, focused-tests, format, lint, types, commit-lint]
    if: always()
    steps:
      - name: Check Status
        run: |
          echo "🎯 ADHD-Optimized CI Pipeline Status"
          echo "✅ Quick Tests: ${{ needs.quick-tests.result }}"
          echo "✅ Focused Tests: ${{ needs.focused-tests.result }}"
          echo "✅ Format: ${{ needs.format.result }}"
          echo "✅ Lint: ${{ needs.lint.result }}"
          echo "✅ Types: ${{ needs.types.result }}"
          echo "✅ Commit Lint: ${{ needs.commit-lint.result }}"
          
          if [[ "${{ needs.quick-tests.result }}" == "failure" || "${{ needs.focused-tests.result }}" == "failure" || "${{ needs.format.result }}" == "failure" || "${{ needs.lint.result }}" == "failure" || "${{ needs.types.result }}" == "failure" || "${{ needs.commit-lint.result }}" == "failure" ]]; then
            echo "❌ CI Pipeline failed"
            exit 1
          fi
          echo "✅ All CI checks passed!"